# Generated by Django 5.0.6 on 2024-05-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clasificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=25, verbose_name="Código")),
                (
                    "descripcion",
                    models.CharField(max_length=100, verbose_name="Descripción"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "ordering": ["descripcion"],
            },
        ),
        migrations.CreateModel(
            name="DatosPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("RC", "REGISTRO CIVIL"),
                            ("TI", "TARJETA DE IDENTIDAD"),
                            ("CC", "CEDULA DE CIUDADANIA"),
                            ("PA", "PASAPORTE"),
                            ("CE", "CEDULA DE EXTRANJERIA"),
                            ("PE", "PERMISO ESPECIAL"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(
                        db_index=True,
                        max_length=25,
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=100, verbose_name="Primer nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo nombre",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=100, verbose_name="Primer apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo apellido",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "edad",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Edad"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "FEMENINO"), ("M", "MASCULINO")],
                        max_length=2,
                        verbose_name="Sexo",
                    ),
                ),
                ("peso", models.FloatField(verbose_name="Peso")),
                ("altura", models.IntegerField(verbose_name="Altura")),
                (
                    "es_estudiante",
                    models.BooleanField(default=False, verbose_name="Es estudiante"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.clasificacion",
                    ),
                ),
            ],
            options={
                "ordering": ["identificacion"],
            },
        ),
    ]
