# Generated by Django 5.0.6 on 2024-06-01 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_alter_clasificacion_codigo_alter_datospersona_altura"),
    ]

    operations = [
        migrations.AddField(
            model_name="datospersona",
            name="imc",
            field=models.FloatField(default=0, verbose_name="IMC"),
        ),
        migrations.AlterField(
            model_name="clasificacion",
            name="codigo",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Solo carácteres permitidos", regex="^[A-Z0-9-]*$"
                    )
                ],
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="datospersona",
            name="altura",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Altura en centímetros"
            ),
        ),
        migrations.AlterField(
            model_name="datospersona",
            name="clasificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion.clasificacion",
            ),
        ),
        migrations.AlterField(
            model_name="datospersona",
            name="peso",
            field=models.FloatField(blank=True, null=True, verbose_name="Peso"),
        ),
    ]
